version: "3"

services:
  db:
    image: postgres:12
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=vocabulary
    volumes:
      - /tmp/vocabulary/data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
  api:
    build: .
    env_file:
      - prod.env
    command: bash -c 'alembic upgrade head && gunicorn api.main:app -b 0.0.0.0:8000 -w 4 -k uvicorn.workers.UvicornWorker'
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
  ui:
    build: frontend/
    command: nginx -g "daemon off;"
    ports:
      - "8080:80"
