"""Added words, user_words tables

Revision ID: 5ea5abbcecc5
Revises: 720af80dffa4
Create Date: 2020-09-20 18:04:27.078782

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ea5abbcecc5'
down_revision = '720af80dffa4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('words',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_words_name'), 'words', ['name'], unique=True)
    op.create_table('user_words',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('word_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['word_id'], ['words.id'], )
    )
    op.create_index('index_user_word', 'user_words', ['user_id', 'word_id'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('index_user_word', table_name='user_words')
    op.drop_table('user_words')
    op.drop_index(op.f('ix_words_name'), table_name='words')
    op.drop_table('words')
    # ### end Alembic commands ###
