"""Users - added email_verified field

Revision ID: 720af80dffa4
Revises: b54f224c749c
Create Date: 2020-09-19 01:21:52.883856

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '720af80dffa4'
down_revision = 'b54f224c749c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email_verified', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'email_verified')
    # ### end Alembic commands ###
