"""UserWord - added primary key

Revision ID: de5c815d1c8f
Revises: 5ea5abbcecc5
Create Date: 2020-09-27 23:27:32.054190

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "de5c815d1c8f"
down_revision = "5ea5abbcecc5"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user_words",
        sa.Column("id", sa.Integer(), primary_key=True),
    )
    op.create_primary_key("user_words_pkey", "user_words", ["id"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user_words", "id")
    # ### end Alembic commands ###
