"""Added words table

Revision ID: 560128ce6445
Revises: 510eb985e53b
Create Date: 2020-09-13 18:10:01.973362

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '560128ce6445'
down_revision = '510eb985e53b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('words',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('word', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_words_id'), 'words', ['id'], unique=False)
    op.create_index(op.f('ix_words_word'), 'words', ['word'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_words_word'), table_name='words')
    op.drop_index(op.f('ix_words_id'), table_name='words')
    op.drop_table('words')
    # ### end Alembic commands ###
